name: 🐛 Bug Report
description: Report a bug
labels: [Bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What is the problem? A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: |
        Provide a self-contained, concise snippet of code that can be used to reproduce the issue.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Behavior
      description: |
        What actually happened?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Information/Context
      description: |
        Anything else that might be relevant for troubleshooting this bug.
        Providing context helps us come up with a solution that is most useful in the real world.
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Compiler version
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment details (OS name and version, etc.)
    validations:
      required: true
